config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resource :session, only: [:new, :create, :destroy]
  resource :authorization, only: :show
end

app/models/menu.rb
class Menu

  def self.get(usuario_id)
    response = RestClient.get("#{ENV['URL_BASE']}/menu/#{usuario_id}")

    JSON.parse(response.body)
  end
end

app/models/usuario.rb
class Usuario < ClienteAPI::Model
  extend ClienteAPI::Integracao::Autenticacao

  attr_accessor :id, :nome, :nome_usuario, :senha, :empresa_id, :admin

  has_many :empresas
  has_many :historico_arquivo_retornos

  def self.login(credenciais={})
    autenticar(credenciais)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :acesso_restrito

  DOMAIN = ENV['GSAN_DOMAIN'] || 'localhost'

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def usuario_autenticado(usuario)
    return nil unless usuario.valid?

    limpar_sessao
    session[:usuario_id] = usuario.id

    setar_cookie
  end

  def usuario_logado
    if session[:usuario_id]
      Usuario.find session[:usuario_id]
    else
      nil
    end
  end

  def acesso_restrito
    if session[:usuario_id]
      @usuario_logado = usuario_logado
      return @usuario_logado unless @usuario_logado.nil?
    end

    limpar_sessao
    redirect_to(new_session_path, alert: "Efetue seu login no GSAN")
  end

  def limpar_sessao
    session.clear
    cookies.delete :gsan, domain: DOMAIN
  end

  def setar_cookie
    value = verifier.generate([usuario_logado.id, 1.week.from_now])

    cookies.delete :gsan, domain: DOMAIN
    cookies.permanent[:gsan] = { value: value, domain: DOMAIN }
  end

  def verifier
    @verifier ||= ActiveSupport::MessageVerifier.new('gsan', serializer: YAML)
  end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  skip_before_action :acesso_restrito

  def show
    token = params[:token]

    begin
      id, expiracao = verifier.verify(token)
    rescue
    end

    if id && Time.zone.now < expiracao
      render text: id, status: :ok
    else
      head :forbidden
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'application'

  def index
    menu = Menu.get(usuario_logado.id)
    @menu = MenuPresenter.new( menu )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :acesso_restrito, only: [:new, :create]
  protect_from_forgery except: :destroy

  layout 'home'

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.login usuario_params

    if usuario_autenticado(@usuario)
      redirect_to(root_path, notice: 'Bem vindo!')
    else
      flash[:alert] = "Login ou senha inválidos"
      render :new
    end
  end

  def destroy
    limpar_sessao

    redirect_to(new_session_path, notice: "Logout efetuado com sucesso!")
  end

  protected

  def usuario_params
    params.require(:usuario).permit(:nome_usuario, :senha)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ICONES_MENU = {
    atendimento_ao_publico: 'fa-users',
    cadastro: 'fa-archive',
    micromedicao: 'fa-battery-full',
    faturamento: 'fa-bar-chart',
    cobranca: 'fa-envelope-o',
    arrecadacao: 'fa-balance-scale',
    relatorios: 'fa-pie-chart',
    gerencial: 'fa-line-chart',
    seguranca: 'fa-lock',
    batch: 'fa-cog',
    financeiro: 'fa-dollar',
    operacional: 'fa-cogs',
    desempenho: 'fa-area-chart'
  }

  def get_icone(modulo)
    nome_modulo = modulo.gsub(' ', '_').underscore.to_sym
    ICONES_MENU[nome_modulo]
  end
end

app/helpers/bootstrap_flash_helper.rb
module BootstrapFlashHelper
  ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg.html_safe, :class => "alert fade in alert-#{type} #{options[:class]}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/views/home/_funcionalidade.html.erb
<ul class="submenu">
  <% funcionalidade[:submenu].each do |funcionalidade| %>
    <% if funcionalidade[:submenu].present? %>
      <li>
        <a class="funcionalidade-pai" href="">
          <%= funcionalidade[:descricao] %>
          <span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
        </a>
        
        <ul class="submenu">
          <% funcionalidade[:submenu].each do |funcionalidade| %>
            <li>
              <a href="<%= funcionalidade[:url] %>"><%= funcionalidade[:descricao] %></a>
            </li>
          <% end -%>
        </ul>
      </li>
    <% else %>
      <li><a href="<%= funcionalidade[:url] %>"> <%= funcionalidade[:descricao] %></a></li>
    <% end -%>
  <% end -%>
</ul>

app/views/home/_funcionalidades.html.erb
<% unless submenu.nil? %>
  <% submenu.each do |funcionalidade| %>
    <% if funcionalidade[:submenu].present? %>
      <li>
        <a class="funcionalidade-pai" href="">
          <%= funcionalidade[:descricao] %> 
          <span><i class="fa fa-caret-right" aria-hidden="true"></i></span>
        </a> 
        
        <%= render partial: "funcionalidade", locals: { funcionalidade: funcionalidade } %>
      </li>
    <% else %>
      <li><a href="<%= funcionalidade[:url] %>"> <%= funcionalidade[:descricao] %></a></li>
    <% end -%>
  <% end -%>
<% end -%>

app/views/home/_submenu.html.erb
<div class="row row-submenu" data-modulo-id="<%= submenu[:id] %>">
  <div class="container-submenu">
    <% inicio = 0 %>
    <% tamanho = 10 %>
    <div class="row">
      <% 3.times do %>
      <div class="col-md-4">
        <ul class="nav nav-pills nav-stacked">
          <% array = submenu[:submenu].slice(inicio, tamanho) %>

          <%= render partial: "funcionalidades", locals: { submenu: array } %>
        </ul>
        <% inicio += tamanho %>
      </div>
      <% end -%>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="input-group search-group">
    <input type="text" class="form-control search-query" placeholder="Pesquisar por funcionalidades">
  </div>
</div>

<% @menu.numero_de_linhas.times do %>
  <div class="row">
    <% @menu[:menu][:submenu].slice(@menu.inicio, @menu.tamanho).each do |submenu| %>
      <div class="col-md-3 m-b-lg">
        <div class="panel panel-modulo panel-default" data-modulo-id="<%= submenu[:id] %>">
          <div class="panel-body">
            <i class="fa <%= get_icone submenu[:descricao] %> fa-4x" aria-hidden="true"></i>

            <h1> <%= submenu[:descricao] %> </h1>
          </div>
        </div>
        <div class="panel-ligacao">

        </div>
      </div>
    <% end -%>
  </div>

  <% @menu[:menu][:submenu].slice(@menu.inicio, @menu.tamanho).each do |submenu| %>
    <% @menu.inicio_submenu = 0 %>
    <%= render partial: "submenu", locals: { submenu: submenu } %>
  <% end -%>

  <% @menu.inicio += @menu.tamanho  %>
<% end -%>

<% content_for :javascript do %>
  <script type="text/javascript">
    $(function(){
      $( ".search-query" ).autocomplete({
        minLength: 2,
        source: <%= raw @menu.converter_hash.to_json %>,
        select: function( event, ui ) {
          window.location.href = ui.item.url;
        }
      });
    });
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GSAN</title>
  <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
</head>
  <body>
   <div class="wrapper" >

    <nav class="top">
      <div class="container-fluid">

        <div class="row">
          <div class="col-md-4">

          </div>
          <div class="col-md-4 brand">
            <span class="brand"><a href="/"><i class="fa fa-tint"></i>GSAN</a></span>
          </div>
          <div class="col-md-4">
            <ul class="top-nav">
              <li class="dropdown">
                <div class="dropdown-toggle dropdown-user" id="dropdownMenu1" data-toggle="dropdown">
                  <%= @usuario_logado.nome %>
                  <span class="caret"></span>
                </div>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li>
                    <%= link_to session_path, method: :delete do %>
                      <i class="fa fa-sign-out"></i> Sair
                    <% end %>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>

    <div class="container-fluid container-main">
      <div class="row">
        <div class="col-md-12 main">
          <div class="container">
            <%= yield %>
          </div>
        </div>
      </div>
    </div> <!-- /container -->
    <!--%= render "shared/footer" %-->
   </div>
   <script type="text/javascript">
     // var BASE_URL = "<%#= API::Base::URL_BASE %>";
   </script>
   <%= javascript_include_tag 'application' %>

   <%= yield :javascript %>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GSAN</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag 'application' %>

    <style type="text/css">
      body {
        background: url(<%= asset_path("cosanpa.jpg") %>) no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
      }
    </style>

  </head>
  <body>
    <div class="container-fluid container-main">
      <div class="row">
        <div class="col-md-12 main">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
      <%#= render "shared/footer" %>
    </div> <!-- /container -->
  </body>
</html>